import type { LocalizedProductContent, ProductSlug } from "@/types/product";

/**
 * Czech product copy. Technical data lives in data/products.ts — this
 * file holds only text, so it can be regenerated by the translations manager.
 */
export const productTextsCz: Record<
  ProductSlug,
  LocalizedProductContent
> = {
  "pudu-t150": {
    name: "AMR T 150",
    category:
      "Autonomní mobilní doručovací robot pro snadnou přepravu materiálu do 150 kg.",
    headline: "Nosnost nákladu do 150kg. Maximální plynulost pohybu.",
    shortDescription:
      "Kompaktní, uživatelsky inteligentní průmyslový AMR robot pro rychlé doručení materiálu.",
    description:
      "Kompaktní průmyslový AMR robot 150 pro doručení zboží pravidelných logistických okruhů. Díky autonomní navigaci, a možnosti integrace se přizpůsobí stávajícímu prostředí, aniž by omezoval jiné úkoly.",
    imageAlt: "Průmyslový AMR robot PUDU T150 s přepravovaným nákladem",
    features: [
      {
        title: "Rychlé nasazení",
        description:
          "Mapování a základní spuštění bez stavebních úprav nebo komplikované infrastruktury.",
      },
      {
        title: "Přesná navigace",
        description:
          "Kombinace VSLAM a LiDAR zajišťuje stabilní pohyb v dynamickém průmyslovém prostředí.",
      },
      {
        title: "Provoz 24/7",
        description:
          "Jednoduchá výměna baterie, automatické i kabelové nabíjení podporují nepřetržitou logistiku.",
      },
    ],
    applications: [
      {
        title: "Zásobování výrobních linek",
        description:
          "Pravidelné doručování dílů a komponentů na montážní pracoviště nebo stanice.",
      },
      {
        title: "Interní přeprava",
        description:
          "Opakované okruhy mezi skladem, přípravou materiálu nebo výrobou.",
      },
      {
        title:
          "Montáž, výroba, sklady, zásobování, obchod, intralogistika, etc.",
        description: "Bezpečný transport materiálu v úzkých prostorách.",
      },
      {
        title: "Nemocnice, laboratoře, školy",
        description:
          "Diskrétní přeprava vzorků, materiálu a spotřebního zboží.",
      },
    ],
    seoTitle: "AMR T150 | Lehká intralogistika | PUDU Industrial",
    seoDescription:
      "AMR T150 — kompaktní autonomní robot s nosností do 150 kg pro díly, komponenty a pravidelné logistické okruhy. Technické parametry, funkce a oblasti využití.",
  },
  "pudu-t300": {
    name: "AMR T 300 (order 2 person)",
    category:
      "Nejprodávanější AMR T 300 Průmyslový autonomní mobilní robot pro přepravu materiálu do 300 kg.",
    headline: "Transport, který se přizpůsobí výrobě.",
    shortDescription:
      "Flexibilní autonomní mobilní vozík pro výrobu, sklady a doručení materiálu. Autonómní vozík T 300 zvládne širokú škálu prepravovaného zboží a zásobování linek.",
    description:
      "Flexibilní autonomní transport pro doručení materiálu do výroby, skladů nebo jde-li o celkové zásobování. Díky autonomní navigaci, bezpečnostním rozhraním a možnosti integrace se přizpůsobí stávajícímu prostředí bez omezení. Spätná väzba",
    imageAlt:
      "Průmyslový robot AMR T 300 s variabilním nákladem s opcí dopravníku a tahání platformy",
    galleryAlt: "AMR T 300 skenuje okolí ve skladové hale",
    features: [
      {
        title: "Autonomní přeprava",
        description:
          "Samostatně doručí materiál na zvolené místo a dynamicky reaguje na změny trasy, bezpečně a plynulo.",
      },
      {
        title: "Režim následování",
        description:
          "Vizuální rozpoznávání umožňuje organizované následování pracovníka nebo dalších robotů.",
      },
      {
        title: "Elektrická asistence",
        description:
          "Při manuálním přesunu pomáhá elektrický pohon a snižuje fyzickou zátěž obsluhy.",
      },
    ],
    applications: [
      {
        title: "Výroba a montážní linky",
        description:
          "Autonomní zásobování pracovišť materiálem podle taktu výroby.",
      },
      {
        title: "Sklady a distribuční centra",
        description:
          "Přeprava mezi příjmem, skladovými zónami a expedicí bez obsluhy.",
      },
      {
        title: "Automotive a elektronika",
        description:
          "Stabilní tok materiálů v prostředí s vysokou vytížeností tras.",
      },
      {
        title: "Smíšený provoz s lidmi",
        description:
          "Režim následování a elektrická asistence při manuálních úlohách.",
      },
    ],
    seoTitle: "AMR T 300 | Univerzální AMR | PUDU Industrial",
    seoDescription:
      "AMR T 300 — univerzální autonomní robot s nosností do 300 kg pro výrobu, sklady a zásobování linek. Technické parametry, funkce a oblasti využití.",
  },
  "pudu-t600-upright": {
    name: "AMR T 600 (Order 2 Person)",
    category:
      "AMR T 600 Průmyslový autonomní mobilní robot pro přepravu těžšího materiálu do 600 kg.",
    headline: "Zvládne i těžkou váhu bez omezení na výkon.",
    shortDescription:
      "Vysokokapacitní platforma s možností presunu palet, krabic, těžkých bremen s ergonomickou rukojetí pro bezpečný přesun těžkých nákladů s možností tahu za vozíkem a zdvihem.",
    description:
      "Robotický vozík T 600 je stavěný pro těžký náklad se kterým si hravě poradí. Jeho vysokokapacitní zesílená platforma s ergonomickou rukojetí a barevným inteligentním displejem umožňuje komunikaci pro bezpečný přesun těžkých nákladů. Díky autonomní navigaci, bezpečnostnímu rozhraní se přizpůsobí svému okolí a doručí zboží na požadované místo.",
    imageAlt: "Průmyslový robot AMR T 600 s ergonomickou rukojetí a displejem.",
    features: [
      {
        title: "Těžký transport",
        description:
          "Nosnost do 600 kg přináší automatizaci palet, vozíků a objemných výrobních nákladů.",
      },
      {
        title: "Asistence obsluze",
        description:
          "Ergonomický ovladač pomáhá pracovníkovi snadno vést robota i s těžkým nákladem.",
      },
      {
        title: "Otevřená integrace",
        description:
          "Podpora protokolu VDA5050 a lokálního nasazení usnadňuje zapojení do podnikových systémů.",
      },
    ],
    applications: [
      {
        title: "Těžké náklady pro plynulou přepravu",
        description:
          "Moving pallets, mobile platforms, and larger loads throughout the entire facility.",
      },
      {
        title: "Mezioperační logistika",
        description:
          "Automatizovaný přesun materiálu s vysokou hmotností přepravovaného nákladu.",
      },
      {
        title:
          "Automotive a strojírenství, zbrojařský průmysl, výroba, montážní pracoviště, intralogistika, obchody, etc.",
        description:
          "Opakovaný transport těžkých komponentů mezi pracovišti a linkami.",
      },
      {
        title: "Integrace do podnikových systémů",
        description:
          "Nasazení v prostředí s protokolem VDA5050 a lokálním řízením flotily.",
      },
    ],
    seoTitle: "AMR T600 | Těžký autonomní transport | PUDU Industrial",
    seoDescription:
      "AMR T600 — autonomní platforma s nosností do 600 kg a ergonomickou rukojetí pro bezpečný přesun těžkých nákladů. Technické parametry a oblasti využití.",
  },
  "pudu-t600-underride": {
    name: "AMR T 600 Podjezdový",
    category:
      "Nízký zvedací podjezdový robotický vozík s výškou zdvihu do 60mm a nosností do 600kg",
    headline:
      "Bezkonkurenční podjezdový vozík s ergonomickou výškou pouhých 250mm ve své kategorii",
    shortDescription:
      "Autonomní robotický vozík AMR 600 typu podjezdový představuje jednoduché a spolehlivé řešení Plug and Play, které se vyznačuje rychlým zavedením do provozu. Jedná se o systémové řešení navržené tak, aby vám poskytlo maximální výkon.",
    description:
      "Nízký autonomní podjezdový AMR robot, který se zasune pod regál, zvedne jej a přemístí. Díky autonomní navigaci, bezpečnostním rizhraním má možnosti integrace kde se přizpůsobí stávajícímu prostředí, aniž by omezil výrobu.",
    imageAlt: "Nízký robotický vozík AMR 600 podjezdový",
    features: [
      {
        title: "Podjezd pod platformu, regál, a jiné konštrukce",
        description:
          "Nízký profil umožňuje autonomní vjezd pod kompatibilní regál nebo rám.",
      },
      {
        title: "Zdvih a transport",
        description:
          "Integrovaný zdvih 60 mm bezpečně převezme náklad a přesune ho na určené místo.",
      },
      {
        title: "Aplikační logistika",
        description:
          "Rozpoznávání skupin regálů a koordinace tras podporují škálovatelnou automatizaci skladu.",
      },
    ],
    applications: [
      {
        title: "Přesun palet, regálů a vozíků, statických či mobilních rámů.",
        description:
          "Autonomní podjezd, zdvih a přemístění celé přepravní jednotky.",
      },
      {
        title: "Skladová automatizace Aplikační logistika, výroba",
        description:
          "Změna toků materiálu bez zásahu do existující infrastruktury.",
      },
      {
        title: "Výroba a mezisklad",
        description:
          "Přesun rozpracované výroby mezi buňkami, linkami a odkládacími zónami.",
      },
      {
        title: "Flotilová logistika",
        description: "Koordinace více robotů a skupin regálů na jedné ploše.",
      },
    ],
    seoTitle: "AMR 600 Podběhový| Nízký zdvihací AMR | PUDU Industrial",
    seoDescription:
      "AMR 600 Podběhový — nízký autonomní robot s nosností do 600 kg, který zajede pod regál s paletou, zvedne ho a přemístí. Technické parametry a oblasti využití.",
  },
};
