import type { LocalizedProductContent, ProductSlug } from "@/types/product";

/**
 * Czech product copy. Technical data lives in data/products.ts — this
 * file holds only text, so it can be regenerated by the translations manager.
 */
export const productTextsCz: Record<
  ProductSlug,
  LocalizedProductContent
> = {
  "pudu-t150": {
    name: "PUDU T150",
    category: "Lehká intralogistika",
    headline: "Lehký náklad. Maximální plynulost.",
    shortDescription:
      "Kompaktní průmyslový robot pro díly, komponenty a pravidelné logistické okruhy.",
    description:
      "Kompaktní průmyslový robot pro díly, komponenty a pravidelné logistické okruhy. Díky autonomní navigaci, bezpečnostním vrstvám a možnosti integrace se přizpůsobí existujícímu prostředí, aniž by výrobu nutil přizpůsobovat se robotu.",
    imageAlt: "Průmyslový robot PUDU T150 s přepravovaným nákladem",
    features: [
      {
        title: "Rychlé nasazení",
        description:
          "Mapování a základní spuštění bez stavebních úprav nebo komplikované infrastruktury.",
      },
      {
        title: "Přesná navigace",
        description:
          "Kombinace VSLAM a LiDAR zajišťuje stabilní pohyb v dynamickém průmyslovém prostředí.",
      },
      {
        title: "Provoz 24/7",
        description:
          "Výměna baterie, automatické i kabelové nabíjení podporují nepřetržitou logistiku.",
      },
    ],
    applications: [
      {
        title: "Zásobování výrobních linek",
        description:
          "Pravidelné doručování dílů a komponentů na montážní pracoviště.",
      },
      {
        title: "Interní přeprava komponentů",
        description:
          "Opakované okruhy mezi skladem, přípravou materiálu a výrobou.",
      },
      {
        title: "Elektronika a přesná výroba",
        description:
          "Šetrný transport citlivých dílů v úzkých a čistých prostorech.",
      },
      {
        title: "Nemocnice a laboratoře",
        description: "Diskrétní převoz vzorků, materiálu a spotřebního zboží.",
      },
    ],
    seoTitle: "PUDU T150 | Lehká intralogistika | PUDU Industrial",
    seoDescription:
      "PUDU T150 — kompaktní autonomní robot s nosností 150 kg pro díly, komponenty a pravidelné logistické okruhy. Technické parametry, funkce a oblasti využití.",
  },
  "pudu-t300": {
    name: "PUDU T300",
    category: "Univerzální AMR",
    headline: "Pohyb, který se přizpůsobí výrobě.",
    shortDescription:
      "Flexibilní autonomní transport pro výrobu, sklady a zásobování linek.",
    description:
      "Flexibilní autonomní transport pro výrobu, sklady a zásobování linek. Díky autonomní navigaci, bezpečnostním vrstvám a možnosti integrace se přizpůsobí existujícímu prostředí, aniž by výrobu nutil přizpůsobovat se robotu.",
    imageAlt: "Průmyslový robot PUDU T300 s kartonovým nákladem",
    galleryAlt: "PUDU T300 skenuje okolí ve skladové hale",
    features: [
      {
        title: "Autonomní přeprava",
        description:
          "Samostatně doručí materiál na zvolené místo a dynamicky reaguje na změny trasy.",
      },
      {
        title: "Režim následování",
        description:
          "Vizuální rozpoznávání umožňuje organizované následování pracovníka nebo dalších robotů.",
      },
      {
        title: "Elektrická asistence",
        description:
          "Při manuálním přesunu pomáhá elektrický pohon a snižuje fyzickou zátěž obsluhy.",
      },
    ],
    applications: [
      {
        title: "Výroba a montážní linky",
        description:
          "Autonomní zásobování pracovišť materiálem podle taktu výroby.",
      },
      {
        title: "Sklady a distribuční centra",
        description:
          "Přeprava mezi příjmem, skladovými zónami a expedicí bez obsluhy.",
      },
      {
        title: "Automotive a elektronika",
        description:
          "Stabilní tok komponentů v prostředí s vysokou vytížeností tras.",
      },
      {
        title: "Smíšený provoz s lidmi",
        description:
          "Režim následování a elektrická asistence při manuálních úlohách.",
      },
    ],
    seoTitle: "PUDU T300 | Univerzální AMR | PUDU Industrial",
    seoDescription:
      "PUDU T300 — univerzální autonomní robot s nosností 300 kg pro výrobu, sklady a zásobování linek. Technické parametry, funkce a oblasti využití.",
  },
  "pudu-t600-upright": {
    name: "PUDU T600 Upright",
    category: "Těžký autonomní transport",
    headline: "Těžká práce. Inteligentně.",
    shortDescription:
      "Vysokokapacitní platforma s ergonomickou rukojetí pro bezpečný přesun těžkých nákladů.",
    description:
      "Vysokokapacitní platforma s ergonomickou rukojetí pro bezpečný přesun těžkých nákladů. Díky autonomní navigaci, bezpečnostním vrstvám a možnosti integrace se přizpůsobí existujícímu prostředí, aniž by výrobu nutil přizpůsobovat se robotu.",
    imageAlt: "Průmyslový robot PUDU T600 Upright s ergonomickou rukojetí",
    features: [
      {
        title: "Těžký transport",
        description:
          "Nosnost 600 kg přináší automatizaci palet, vozíků a objemných výrobních nákladů.",
      },
      {
        title: "Asistence obsluze",
        description:
          "Ergonomický ovladač pomáhá pracovníkovi snadno vést robota i s těžkým nákladem.",
      },
      {
        title: "Otevřená integrace",
        description:
          "Podpora protokolu VDA5050 a lokálního nasazení usnadňuje zapojení do podnikových systémů.",
      },
    ],
    applications: [
      {
        title: "Těžké výrobní náklady",
        description:
          "Přesun palet, vozíků a objemných dílů v rámci celého provozu.",
      },
      {
        title: "Mezioperační logistika",
        description:
          "Automatizace delších tras s vysokou hmotností přepravovaného nákladu.",
      },
      {
        title: "Automotive a strojírenství",
        description:
          "Opakovaný transport těžkých komponentů mezi pracovišti a linkami.",
      },
      {
        title: "Integrace do podnikových systémů",
        description:
          "Nasazení v prostředí s protokolem VDA5050 a lokálním řízením flotily.",
      },
    ],
    seoTitle: "PUDU T600 Upright | Těžký autonomní transport | PUDU Industrial",
    seoDescription:
      "PUDU T600 Upright — autonomní platforma s nosností 600 kg a ergonomickou rukojetí pro bezpečný přesun těžkých nákladů. Technické parametry a oblasti využití.",
  },
  "pudu-t600-underride": {
    name: "PUDU T600 Underride",
    category: "Nízký zdvihací AMR",
    headline: "Pod nákladem. Nad očekávání.",
    shortDescription:
      "Nízký autonomní podjezdový robot, který zajede pod regál, zvedne ho a přemístí.",
    description:
      "Nízký autonomní podjezdový robot, který zajede pod regál, zvedne ho a přemístí. Díky autonomní navigaci, bezpečnostním vrstvám a možnosti integrace se přizpůsobí existujícímu prostředí, aniž by výrobu nutil přizpůsobovat se robotu.",
    imageAlt: "Nízký podjezdový robot PUDU T600 Underride",
    features: [
      {
        title: "Podjezd pod regál",
        description:
          "Nízký profil umožňuje autonomní vjezd pod kompatibilní regál nebo vozík.",
      },
      {
        title: "Zdvih a transport",
        description:
          "Integrovaný zdvih 60 mm bezpečně převezme náklad a přesune ho na určené místo.",
      },
      {
        title: "Flotilová logistika",
        description:
          "Rozpoznávání skupin regálů a koordinace tras podporují škálovatelnou automatizaci skladu.",
      },
    ],
    applications: [
      {
        title: "Přesun regálů a vozíků",
        description:
          "Autonomní podjezd, zdvih a přemístění celé přepravní jednotky.",
      },
      {
        title: "Skladová automatizace",
        description:
          "Změna toků materiálu bez zásahu do existující infrastruktury.",
      },
      {
        title: "Výroba a mezisklad",
        description:
          "Přesun rozpracované výroby mezi buňkami, linkami a odkládacími zónami.",
      },
      {
        title: "Flotilová logistika",
        description: "Koordinace více robotů a skupin regálů na jedné ploše.",
      },
    ],
    seoTitle: "PUDU T600 Underride | Nízký zdvihací AMR | PUDU Industrial",
    seoDescription:
      "PUDU T600 Underride — nízký autonomní robot s nosností 600 kg, který zajede pod regál, zvedne ho a přemístí. Technické parametry a oblasti využití.",
  },
};
