import type { LocalizedProductContent, ProductSlug } from "@/types/product";

/**
 * German product copy. Technical data lives in data/products.ts — this
 * file holds only text, so it can be regenerated by the translations manager.
 */
export const productTextsDe: Record<
  ProductSlug,
  LocalizedProductContent
> = {
  "pudu-t150": {
    name: "PUDU T150",
    category: "Leichte Intralogistik",
    headline: "Leichte Last. Maximaler Fluss.",
    shortDescription:
      "Ein kompakter Industrieroboter für Teile, Bauteile und wiederkehrende Logistikrunden.",
    description:
      "Ein kompakter Industrieroboter für Teile, Bauteile und wiederkehrende Logistikrunden. Autonome Navigation, mehrschichtige Sicherheit und offene Integration lassen ihn sich an Ihre bestehende Umgebung anpassen — statt den Betrieb zum Roboter zu zwingen.",
    imageAlt: "Industrieroboter PUDU T150 mit transportierter Last",
    features: [
      {
        title: "Schnelle Inbetriebnahme",
        description:
          "Kartierung und Start ohne Baumaßnahmen oder komplizierte Infrastruktur.",
      },
      {
        title: "Präzise Navigation",
        description:
          "VSLAM in Kombination mit LiDAR hält die Bewegung im dynamischen Industrieumfeld stabil.",
      },
      {
        title: "Betrieb rund um die Uhr",
        description:
          "Batteriewechsel sowie automatisches und Kabelladen tragen eine unterbrechungsfreie Logistik.",
      },
    ],
    applications: [
      {
        title: "Versorgung der Produktionslinien",
        description:
          "Regelmäßige Zulieferung von Teilen und Bauteilen an die Montageplätze.",
      },
      {
        title: "Interner Bauteiltransport",
        description:
          "Wiederkehrende Runden zwischen Lager, Materialbereitstellung und Produktion.",
      },
      {
        title: "Elektronik und Präzisionsfertigung",
        description:
          "Schonender Transport empfindlicher Teile durch enge und reine Bereiche.",
      },
      {
        title: "Krankenhäuser und Labore",
        description:
          "Diskreter Transport von Proben, Material und Verbrauchsgütern.",
      },
    ],
    seoTitle: "PUDU T150 | Leichte Intralogistik | PUDU Industrial",
    seoDescription:
      "PUDU T150 — kompakter autonomer Roboter mit 150 kg Traglast für Teile, Bauteile und wiederkehrende Logistikrunden. Technische Daten, Funktionen und Einsatzbereiche.",
  },
  "pudu-t300": {
    name: "PUDU T300",
    category: "Universeller AMR",
    headline: "Bewegung, die sich der Produktion anpasst.",
    shortDescription:
      "Flexibler autonomer Transport für Produktion, Lager und Linienversorgung.",
    description:
      "Flexibler autonomer Transport für Produktion, Lager und Linienversorgung. Autonome Navigation, mehrschichtige Sicherheit und offene Integration lassen ihn sich an Ihre bestehende Umgebung anpassen — statt den Betrieb zum Roboter zu zwingen.",
    imageAlt: "Industrieroboter PUDU T300 mit Kartonlast",
    galleryAlt: "PUDU T300 scannt seine Umgebung in einer Lagerhalle",
    features: [
      {
        title: "Autonomer Transport",
        description:
          "Liefert Material selbstständig an den gewählten Ort und reagiert dynamisch auf Routenänderungen.",
      },
      {
        title: "Folgemodus",
        description:
          "Visuelle Erkennung ermöglicht ein geordnetes Folgen des Mitarbeiters oder weiterer Roboter.",
      },
      {
        title: "Elektrische Unterstützung",
        description:
          "Beim manuellen Verschieben hilft der elektrische Antrieb und senkt die körperliche Belastung.",
      },
    ],
    applications: [
      {
        title: "Produktion und Montagelinien",
        description:
          "Autonome Materialversorgung der Arbeitsplätze im Takt der Produktion.",
      },
      {
        title: "Lager und Distributionszentren",
        description:
          "Transport zwischen Wareneingang, Lagerzonen und Versand ohne Bedienung.",
      },
      {
        title: "Automotive und Elektronik",
        description:
          "Stabiler Bauteilfluss in Umgebungen mit stark genutzten Routen.",
      },
      {
        title: "Gemeinsamer Betrieb mit Menschen",
        description:
          "Folgemodus und elektrische Unterstützung für den manuellen Teil der Arbeit.",
      },
    ],
    seoTitle: "PUDU T300 | Universeller AMR | PUDU Industrial",
    seoDescription:
      "PUDU T300 — universeller autonomer Roboter mit 300 kg Traglast für Produktion, Lager und Linienversorgung. Technische Daten, Funktionen und Einsatzbereiche.",
  },
  "pudu-t600-upright": {
    name: "PUDU T600 Upright",
    category: "Autonomer Schwerlasttransport",
    headline: "Schwere Arbeit. Intelligent gelöst.",
    shortDescription:
      "Eine Plattform mit hoher Kapazität und ergonomischem Griff für den sicheren Transport schwerer Lasten.",
    description:
      "Eine Plattform mit hoher Kapazität und ergonomischem Griff für den sicheren Transport schwerer Lasten. Autonome Navigation, mehrschichtige Sicherheit und offene Integration lassen sie sich an Ihre bestehende Umgebung anpassen — statt den Betrieb zum Roboter zu zwingen.",
    imageAlt: "Industrieroboter PUDU T600 Upright mit ergonomischem Griff",
    features: [
      {
        title: "Schwerlasttransport",
        description:
          "600 kg Traglast bringen Automatisierung zu Paletten, Wagen und sperrigen Produktionslasten.",
      },
      {
        title: "Unterstützung der Bedienung",
        description:
          "Der ergonomische Griff macht das Führen des Roboters auch mit schwerer Last einfach.",
      },
      {
        title: "Offene Integration",
        description:
          "Die Unterstützung von VDA5050 und lokalem Betrieb erleichtert die Anbindung an Unternehmenssysteme.",
      },
    ],
    applications: [
      {
        title: "Schwere Produktionslasten",
        description:
          "Verschieben von Paletten, Wagen und sperrigen Teilen im gesamten Betrieb.",
      },
      {
        title: "Zwischenbetriebliche Logistik",
        description: "Automatisierung längerer Routen mit hohem Lastgewicht.",
      },
      {
        title: "Automotive und Maschinenbau",
        description:
          "Wiederkehrender Transport schwerer Bauteile zwischen Arbeitsplätzen und Linien.",
      },
      {
        title: "Anbindung an Unternehmenssysteme",
        description:
          "Einsatz in Umgebungen mit VDA5050-Protokoll und lokaler Flottensteuerung.",
      },
    ],
    seoTitle:
      "PUDU T600 Upright | Autonomer Schwerlasttransport | PUDU Industrial",
    seoDescription:
      "PUDU T600 Upright — autonome Plattform mit 600 kg Traglast und ergonomischem Griff für den sicheren Transport schwerer Lasten. Technische Daten und Einsatzbereiche.",
  },
  "pudu-t600-underride": {
    name: "PUDU T600 Underride",
    category: "Flacher Hub-AMR",
    headline: "Unter der Last. Über den Erwartungen.",
    shortDescription:
      "Ein flacher autonomer Unterfahr-Roboter, der unter ein Regal fährt, es anhebt und verfährt.",
    description:
      "Ein flacher autonomer Unterfahr-Roboter, der unter ein Regal fährt, es anhebt und verfährt. Autonome Navigation, mehrschichtige Sicherheit und offene Integration lassen ihn sich an Ihre bestehende Umgebung anpassen — statt den Betrieb zum Roboter zu zwingen.",
    imageAlt: "Flacher Unterfahr-Roboter PUDU T600 Underride",
    features: [
      {
        title: "Unterfahren des Regals",
        description:
          "Das flache Profil erlaubt die autonome Einfahrt unter ein kompatibles Regal oder einen Wagen.",
      },
      {
        title: "Anheben und Transport",
        description:
          "Der integrierte Hub von 60 mm übernimmt die Last sicher und bringt sie an den Zielort.",
      },
      {
        title: "Flottenlogistik",
        description:
          "Erkennung von Regalgruppen und Routenkoordination tragen eine skalierbare Lagerautomatisierung.",
      },
    ],
    applications: [
      {
        title: "Verfahren von Regalen und Wagen",
        description:
          "Autonomes Unterfahren, Anheben und Umsetzen einer kompletten Transporteinheit.",
      },
      {
        title: "Lagerautomatisierung",
        description:
          "Materialflüsse neu ordnen, ohne die bestehende Infrastruktur anzutasten.",
      },
      {
        title: "Produktion und Zwischenlager",
        description:
          "Verfahren angearbeiteter Ware zwischen Zellen, Linien und Pufferflächen.",
      },
      {
        title: "Flottenlogistik",
        description:
          "Koordination mehrerer Roboter und Regalgruppen auf einer Fläche.",
      },
    ],
    seoTitle: "PUDU T600 Underride | Flacher Hub-AMR | PUDU Industrial",
    seoDescription:
      "PUDU T600 Underride — flacher autonomer Roboter mit 600 kg Traglast, der unter ein Regal fährt, es anhebt und verfährt. Technische Daten und Einsatzbereiche.",
  },
};
