import type { LocalizedProductContent, ProductSlug } from "@/types/product";

/**
 * German product copy. Technical data lives in data/products.ts — this
 * file holds only text, so it can be regenerated by the translations manager.
 */
export const productTextsDe: Record<
  ProductSlug,
  LocalizedProductContent
> = {
  "pudu-t150": {
    name: "AMR T 150",
    category:
      "Autonomer mobiler Lieferroboter für den Leichttransport von Materialien bis zu 150 kg.",
    headline: "Tragfähigkeit bis zu 150 kg. Höchste Laufruhe.",
    shortDescription:
      "Ein kompakter, benutzerfreundlicher industrieller AMR-Roboter für den schnellen Materialtransport.",
    description:
      "Der kompakte Industrie-Roboter AMR 150 ist für die Warenzustellung innerhalb regulärer Logistik-Kreisläufe konzipiert. Dank autonomer Navigation und Integrationsfähigkeit passt er sich an die bestehende Umgebung an, ohne andere Abläufe zu beeinträchtigen.",
    imageAlt: "Industrieroboter PUDU AMR T150 mit transportierter Last",
    features: [
      {
        title: "Schnelle Inbetriebnahme",
        description:
          "Kartierung und Start ohne Baumaßnahmen oder komplizierte Infrastruktur.",
      },
      {
        title: "Präzise Navigation",
        description:
          "VSLAM in Kombination mit LiDAR hält die Bewegung im dynamischen Industrieumfeld stabil.",
      },
      {
        title: "Betrieb rund um die Uhr",
        description:
          "Simple batteriewechsel sowie automatisches und Kabelladen tragen eine unterbrechungsfreie Logistik.",
      },
    ],
    applications: [
      {
        title: "Versorgung der Produktionslinien",
        description:
          "Regelmäßige Zulieferung von Teilen und Bauteilen an die Montageplätze.",
      },
      {
        title: "Interner Bauteiltransport",
        description:
          "Wiederkehrende Runden zwischen Lager, Materialbereitstellung und Produktion.",
      },
      {
        title:
          "Montage, Produktion, Lagerhaltung, Versorgung, Vertrieb, Intralogistik usw.",
        description: "Sicherer Materialtransport auf engem Raum.",
      },
      {
        title: "Krankenhäuser und Labore",
        description:
          "Diskreter Transport von Proben, Material und Verbrauchsgütern.",
      },
    ],
    seoTitle: "AMR T150 | Leichte Intralogistik | PUDU Industrial",
    seoDescription:
      "AMR T150 — kompakter autonomer Roboter mit 150 kg Traglast für Teile, Bauteile und wiederkehrende Logistikrunden. Technische Daten, Funktionen und Einsatzbereiche.",
  },
  "pudu-t300": {
    name: "AMR T 300",
    category:
      "Der Bestseller AMR T 300 Industrieller autonomer mobiler Roboter für den Materialtransport zu 300 kg.",
    headline: "Transport, die sich der Produktion anpasst.",
    shortDescription:
      "Flexibler autonomer Transport für Produktion, Lager und Linienversorgung.",
    description:
      "Flexibler, autonomer Transport für die Materialversorgung von Produktionsbereichen oder Lagern sowie für allgemeine Versorgungsaufgaben. Dank autonomer Navigation, Sicherheitsschnittstellen und Integrationsfähigkeit fügt sich das System nahtlos in die bestehende Umgebung ein.",
    imageAlt:
      "Industrieroboter AMR T 300 mit variabler Tragfähigkeit, ausgestattet mit Optionen für Fördertechnik und Plattformzug.",
    galleryAlt: "AMR T 300 scannt seine Umgebung in einer Lagerhalle",
    features: [
      {
        title: "Autonomer Transport",
        description:
          "Es transportiert Material autonom an den gewählten Ort und reagiert sicher und reibungslos auf Routenänderungen.",
      },
      {
        title: "Folgemodus",
        description:
          "Visuelle Erkennung ermöglicht ein geordnetes Folgen des Mitarbeiters oder weiterer Roboter.",
      },
      {
        title: "Elektrische Unterstützung",
        description:
          "Beim manuellen Verschieben hilft der elektrische Antrieb und senkt die körperliche Belastung.",
      },
    ],
    applications: [
      {
        title: "Produktion und Montagelinien",
        description:
          "Autonome Materialversorgung der Arbeitsplätze im Takt der Produktion.",
      },
      {
        title: "Lager und Distributionszentren",
        description:
          "Transport zwischen Wareneingang, Lagerzonen und Versand ohne Bedienung.",
      },
      {
        title: "Automotive und Elektronik",
        description:
          "Stabiler Bauteilfluss in Umgebungen mit stark genutzten Routen.",
      },
      {
        title: "Gemeinsamer Betrieb mit Menschen",
        description:
          "Folgemodus und elektrische Unterstützung für den manuellen Teil der Arbeit.",
      },
    ],
    seoTitle: "AMR T 300 | Universeller AMR | PUDU Industrial",
    seoDescription:
      "AMR T 300 — universeller autonomer Roboter mit 300 kg Traglast für Produktion, Lager und Linienversorgung. Technische Daten, Funktionen und Einsatzbereiche.",
  },
  "pudu-t600-upright": {
    name: "AMR T 600",
    category:
      "AMR T 600 – ein autonomer Industrieroboter für den Transport schwerer Materialien mit einem Gewicht von bis zu 600 kg.",
    headline:
      "Es bewältigt selbst hohe Lasten, ohne dass die Leistung beeinträchtigt wird.",
    shortDescription:
      "Hochleistungsplattform mit ergonomischem Griff für den sicheren Transport schwerer Lasten, ausgestattet mit Zug- und Hebefunktionen.",
    description:
      "Der Roboter-Transportwagen T 600 ist darauf ausgelegt, schwere Lasten mühelos zu bewältigen. Seine verstärkte Plattform mit hoher Tragfähigkeit – ausgestattet mit einem ergonomischen Griff und einem intelligenten Farbdisplay – ermöglicht die Kommunikation für den sicheren Transport schwerer Lasten. Dank autonomer Navigation und einer Sicherheitsschnittstelle passt er sich seiner Umgebung an und liefert Waren an den gewünschten Ort.",
    imageAlt: "Industrieroboter AMR T 600 mit ergonomischem Griff und Display.",
    features: [
      {
        title: "Schwerlasttransport",
        description:
          "Bis zu 600 kg Nutzlast bringen Automatisierung zu Paletten, Wagen und sperrigen Produktionslasten.",
      },
      {
        title: "Unterstützung der Bedienung",
        description:
          "Der ergonomische Griff macht das Führen des Roboters auch mit schwerer Last einfach.",
      },
      {
        title: "Offene Integration",
        description:
          "Die Unterstützung von VDA5050 und lokalem Betrieb erleichtert die Anbindung an Unternehmenssysteme.",
      },
    ],
    applications: [
      {
        title: "Schwere Lasten für einen reibungslosen Transport",
        description:
          "Transport von Paletten, mobilen Plattformen und größeren Lasten im gesamten Betriebsgelände.",
      },
      {
        title: "Zwischenbetriebliche Logistik",
        description: "Automatisierte Materialhandhabung für schwere Lasten.",
      },
      {
        title:
          "Automobil- und Maschinenbau, Rüstungsindustrie, Fertigung, Montagearbeitsplätze, Intralogistik, Einzelhandel usw.",
        description:
          "Wiederkehrender Transport schwerer Bauteile zwischen Arbeitsplätzen und Linien.",
      },
      {
        title: "Anbindung an Unternehmenssysteme",
        description:
          "Einsatz in Umgebungen mit VDA5050-Protokoll und lokaler Flottensteuerung.",
      },
    ],
    seoTitle: "AMR T600 | Autonomer Schwerlasttransport | PUDU Industrial",
    seoDescription:
      "AMR T600 — autonome Plattform mit 600 kg Traglast und ergonomischem Griff für den sicheren Transport schwerer Lasten. Technische Daten und Einsatzbereiche.",
  },
  "pudu-t600-underride": {
    name: "PUDU T 600 Underride",
    category:
      "Flaches, robotergestütztes Unterfahrfahrzeug mit einer Hubhöhe von bis zu 60 mm und einer Tragfähigkeit von bis zu 600 kg",
    headline: "Unter der Last. Über den Erwartungen.",
    shortDescription:
      "Der autonome Unterfahrroboter 600 ist eine zuverlässige Plug-and-Play-Lösung, die sich durch Einfachheit, Ergonomie und hochwertiges Design auszeichnet. Es handelt sich um ein technisches System, das für maximale Leistung sorgt.",
    description:
      "Ein flacher, autonomer AMR, der unter ein Regal fährt, dieses anhebt und transportiert. Dank autonomer Navigation und Sicherheitsschnittstellen bietet er Integrationsmöglichkeiten, die eine Anpassung an die bestehende Umgebung ohne Unterbrechung der Produktion ermöglichen.",
    imageAlt: "Flacher mobiler Roboter AMR 600 Unterfahr",
    features: [
      {
        title: "Unterfahren des platforma, regals",
        description:
          "Das flache Profil erlaubt die autonome Einfahrt unter ein kompatibles Regal oder einen Wagen.",
      },
      {
        title: "Anheben und Transport",
        description:
          "Der integrierte Hub von 60 mm übernimmt die Last sicher und bringt sie an den Zielort.",
      },
      {
        title: "Flottenlogistik",
        description:
          "Erkennung von Regalgruppen und Routenkoordination tragen eine skalierbare Lagerautomatisierung.",
      },
    ],
    applications: [
      {
        title:
          "Verlagerung von Paletten, Regalsystemen und Transportwagen sowie von stationären oder mobilen Gestellen.",
        description:
          "Autonomes Unterfahren, Anheben und Umsetzen einer kompletten Transporteinheit.",
      },
      {
        title: "Lagerautomatisierung Anwendungsbereiche: Logistik, Fertigung",
        description:
          "Materialflüsse neu ordnen, ohne die bestehende Infrastruktur anzutasten.",
      },
      {
        title: "Produktion und Zwischenlager",
        description:
          "Verfahren angearbeiteter Ware zwischen Zellen, Linien und Pufferflächen.",
      },
      {
        title: "Flottenlogistik",
        description:
          "Koordination mehrerer Roboter und Regalgruppen auf einer Fläche.",
      },
    ],
    seoTitle: "AMR 600 Underride | Flacher Hub-AMR | PUDU Industrial",
    seoDescription:
      "AMR 600 Underride — flacher autonomer Roboter mit 600 kg Traglast, der unter ein Regal fährt, es anhebt und verfährt. Technische Daten und Einsatzbereiche.",
  },
};
