import type { LocalizedProductContent, ProductSlug } from "@/types/product";

/**
 * English product copy. Technical data lives in data/products.ts — this
 * file holds only text, so it can be regenerated by the translations manager.
 */
export const productTextsEn: Record<
  ProductSlug,
  LocalizedProductContent
> = {
  "pudu-t150": {
    name: "AMR T 150",
    category:
      "Autonomous mobile delivery robot for the light transport of materials up to 150 kg.",
    headline: "Load capacity up to 150 kg. Maximum smoothness of movement.",
    shortDescription:
      "A compact, user-friendly industrial AMR robot for rapid material delivery.",
    description:
      "The compact industrial AMR 150 robot is designed for goods delivery within regular logistics loops. Thanks to autonomous navigation and integration capabilities, it adapts to the existing environment without interfering with other tasks.",
    imageAlt: "PUDU T150 industrial AMR robot carrying a load",
    features: [
      {
        title: "Fast deployment",
        description:
          "Mapping and initial start-up without construction work or complicated infrastructure.",
      },
      {
        title: "Precise navigation",
        description:
          "VSLAM combined with LiDAR keeps motion stable in a dynamic industrial environment.",
      },
      {
        title: "24/7 operation",
        description:
          "Simple battery swap plus automatic and cable charging support uninterrupted logistics.",
      },
    ],
    applications: [
      {
        title: "Production line supply",
        description:
          "Regular delivery of parts and components to assembly workstations or other delivery stations.",
      },
      {
        title: "Internal transport",
        description:
          "Repeating loops between the warehouse, material preparation and production.",
      },
      {
        title:
          "Assembly, production, warehousing, supply, sales, intralogistics, etc.",
        description: "Safe material transport in narrow spaces.",
      },
      {
        title: "Hospitals, laboratories, schools",
        description:
          "Discreet transport of samples, materials and consumables.",
      },
    ],
    seoTitle: "AMR T150 | Light intralogistics | PUDU Industrial",
    seoDescription:
      "AMR T150 — a compact autonomous robot up to 150 kg payload for parts, components and recurring logistics loops. Specifications, features and applications.",
  },
  "pudu-t300": {
    name: "AMR T 300 (order 2 person)",
    category:
      "Best-selling AMR T 300 Industrial autonomous mobile robot for material transport up to 300 kg.",
    headline: "Transport that adapts to production.",
    shortDescription:
      "Flexible autonomous transport for manufacturing, warehouses and line supply.",
    description:
      "Flexible autonomous transport for delivering materials to production areas or warehouses, or for general supply operations. Thanks to autonomous navigation, safety interfaces, and integration capabilities, it adapts seamlessly to the existing environment.",
    imageAlt:
      "AMR T 300 industrial robot with variable load capacity, featuring conveyor and platform-towing options.",
    galleryAlt: "AMR T 300 scanning its surroundings inside a warehouse",
    features: [
      {
        title: "Autonomous transport",
        description:
          "Delivers material to the chosen location on its own and reacts dynamically to route changes, safely and smoothly.",
      },
      {
        title: "Follow mode",
        description:
          "Visual recognition allows organised following of a worker or of other robots.",
      },
      {
        title: "Powered assistance",
        description:
          "During manual moves the electric drive assists the operator and reduces physical strain.",
      },
    ],
    applications: [
      {
        title: "Manufacturing and assembly lines",
        description:
          "Autonomous material supply to workstations in line with the production cycle.",
      },
      {
        title: "Warehouses and distribution centres",
        description:
          "Unattended transport between goods-in, storage zones and dispatch.",
      },
      {
        title: "Automotive and electronics",
        description:
          "A stable flow of materials in environments with heavily used routes.",
      },
      {
        title: "Shared operation with people",
        description:
          "Follow mode and powered assistance for the manual part of the job.",
      },
    ],
    seoTitle: "AMR T 300 | Versatile AMR | PUDU Industrial",
    seoDescription:
      "AMR T 300 — a versatile autonomous robot up to 300 kg payload for manufacturing, warehouses and line supply. Specifications, features and applications.",
  },
  "pudu-t600-upright": {
    name: "AMR T 600 (Order 2 Person)",
    category:
      "AMR T 600 – an industrial autonomous robot for transporting heavy materials weighing up to 600 kg.",
    headline: "It handles even heavy loads without compromising performance.",
    shortDescription:
      "High-capacity platform with an ergonomic handle for the safe transport of heavy loads, pallets featuring towing and lifting capabilities.",
    description:
      "The T 600 robotic cart is built to handle heavy loads with ease. Its high-capacity, reinforced platform—featuring an ergonomic handle and a smart color display—facilitates communication for the safe transport of heavy loads. Thanks to autonomous navigation and a safety interface, it adapts to its surroundings and delivers goods to the desired location.",
    imageAlt:
      "AMR T 600 industrial robot with an ergonomic handle and a display.",
    features: [
      {
        title: "Heavy transport",
        description:
          "Up to 600 kg payload brings automation to pallets, trolleys and bulky production loads.",
      },
      {
        title: "Operator assistance",
        description:
          "The ergonomic control makes it easy to guide the robot even with a heavy load.",
      },
      {
        title: "Open integration",
        description:
          "VDA5050 support and on-premise deployment simplify the link to enterprise systems.",
      },
    ],
    applications: [
      {
        title: "Heavy loads for smooth transport",
        description:
          "Moving pallets, mobile platforms, and larger loads throughout the entire facility.",
      },
      {
        title: "Inter-process logistics",
        description: "Automated material handling for heavy loads.",
      },
      {
        title:
          "Automotive and mechanical engineering, defense industry, manufacturing, assembly workstations, intralogistics, retail, etc.",
        description:
          "Repeated transport of heavy components between workplaces and lines.",
      },
      {
        title: "Enterprise system integration",
        description:
          "Deployment in environments with the VDA5050 protocol and local fleet control.",
      },
    ],
    seoTitle: "AMR T600 | Heavy-duty autonomous transport | PUDU Industrial",
    seoDescription:
      "AMR T600 — an autonomous platform up to 600 kg payload and an ergonomic handle for moving heavy loads safely. Specifications and applications.",
  },
  "pudu-t600-underride": {
    name: "AMR T 600 Underride",
    category:
      "Low-profile robotic under-ride vehicle with a lifting height of up to 60 mm and a load capacity of up to 600 kg",
    headline:
      "The best underride AMR robot with an ergonomic height of just 250 mm.",
    shortDescription:
      "Autonomous under-ride robot 600 is simple reliable for plug and play solution and designed to be simple, ergonomic and high quality design. It is solution engineering system which gives you maximum performace.",
    description:
      "A low-profile, autonomous AMR that slides under a rack, lifts it, and moves it. Thanks to autonomous navigation and safety interfaces, it offers integration capabilities that allow it to adapt to the existing environment without disrupting production.",
    imageAlt: "AMR 600 Underride autonomous robot",
    features: [
      {
        title: "Drives under the platform, rucks",
        description:
          "The low profile allows autonomous entry underneath a compatible rack or trolley.",
      },
      {
        title: "Lift and transport",
        description:
          "The integrated 60 mm lift picks the load up safely and moves it to the target location.",
      },
      {
        title: "Fleet logistics",
        description:
          "Rack-group recognition and route coordination support scalable warehouse automation.",
      },
    ],
    applications: [
      {
        title:
          "Relocation of pallets, shelving units, and trolleys, as well as static or mobile frames.",
        description:
          "Autonomous entry, lift and relocation of a complete transport unit.",
      },
      {
        title: "Warehouse Automation Application Logistics, Manufacturing",
        description:
          "Reshaping material flows without touching the existing infrastructure.",
      },
      {
        title: "Production and buffer storage",
        description:
          "Moving work in progress between cells, lines and staging areas.",
      },
      {
        title: "Fleet logistics",
        description:
          "Coordinating several robots and rack groups across a single floor.",
      },
    ],
    seoTitle: "AMR 600 Underride | Low-profile lifting AMR | PUDU Industrial",
    seoDescription:
      "AMR 600 Underride — a low-profile autonomous robot up to 600 kg payload that drives under a rack, lifts it and moves it. Specifications and applications.",
  },
};
