import type { LocalizedProductContent, ProductSlug } from "@/types/product";

/**
 * English product copy. Technical data lives in data/products.ts — this
 * file holds only text, so it can be regenerated by the translations manager.
 */
export const productTextsEn: Record<
  ProductSlug,
  LocalizedProductContent
> = {
  "pudu-t150": {
    name: "PUDU T150",
    category: "Light intralogistics",
    headline: "Light loads. Maximum flow.",
    shortDescription:
      "A compact industrial robot for parts, components and recurring logistics loops.",
    description:
      "A compact industrial robot for parts, components and recurring logistics loops. Autonomous navigation, layered safety and open integration let it adapt to your existing environment instead of forcing your operation to adapt to the robot.",
    imageAlt: "PUDU T150 industrial robot carrying a load",
    features: [
      {
        title: "Fast deployment",
        description:
          "Mapping and initial start-up without construction work or complicated infrastructure.",
      },
      {
        title: "Precise navigation",
        description:
          "VSLAM combined with LiDAR keeps motion stable in a dynamic industrial environment.",
      },
      {
        title: "24/7 operation",
        description:
          "Battery swap plus automatic and cable charging support uninterrupted logistics.",
      },
    ],
    applications: [
      {
        title: "Production line supply",
        description:
          "Regular delivery of parts and components to assembly workstations.",
      },
      {
        title: "Internal component transport",
        description:
          "Repeating loops between the warehouse, material preparation and production.",
      },
      {
        title: "Electronics and precision manufacturing",
        description:
          "Gentle transport of sensitive parts through narrow and clean spaces.",
      },
      {
        title: "Hospitals and laboratories",
        description:
          "Discreet transport of samples, materials and consumables.",
      },
    ],
    seoTitle: "PUDU T150 | Light intralogistics | PUDU Industrial",
    seoDescription:
      "PUDU T150 — a compact autonomous robot with a 150 kg payload for parts, components and recurring logistics loops. Specifications, features and applications.",
  },
  "pudu-t300": {
    name: "PUDU T300",
    category: "Versatile AMR",
    headline: "Movement that adapts to production.",
    shortDescription:
      "Flexible autonomous transport for manufacturing, warehouses and line supply.",
    description:
      "Flexible autonomous transport for manufacturing, warehouses and line supply. Autonomous navigation, layered safety and open integration let it adapt to your existing environment instead of forcing your operation to adapt to the robot.",
    imageAlt: "PUDU T300 industrial robot carrying a cardboard load",
    galleryAlt: "PUDU T300 scanning its surroundings inside a warehouse",
    features: [
      {
        title: "Autonomous transport",
        description:
          "Delivers material to the chosen location on its own and reacts dynamically to route changes.",
      },
      {
        title: "Follow mode",
        description:
          "Visual recognition allows organised following of a worker or of other robots.",
      },
      {
        title: "Powered assistance",
        description:
          "During manual moves the electric drive assists the operator and reduces physical strain.",
      },
    ],
    applications: [
      {
        title: "Manufacturing and assembly lines",
        description:
          "Autonomous material supply to workstations in line with the production cycle.",
      },
      {
        title: "Warehouses and distribution centres",
        description:
          "Unattended transport between goods-in, storage zones and dispatch.",
      },
      {
        title: "Automotive and electronics",
        description:
          "A stable flow of components in environments with heavily used routes.",
      },
      {
        title: "Shared operation with people",
        description:
          "Follow mode and powered assistance for the manual part of the job.",
      },
    ],
    seoTitle: "PUDU T300 | Versatile AMR | PUDU Industrial",
    seoDescription:
      "PUDU T300 — a versatile autonomous robot with a 300 kg payload for manufacturing, warehouses and line supply. Specifications, features and applications.",
  },
  "pudu-t600-upright": {
    name: "PUDU T600 Upright",
    category: "Heavy-duty AMR",
    headline: "Heavy work, handled intelligently.",
    shortDescription:
      "A high-capacity platform with an ergonomic handle for moving heavy loads safely.",
    description:
      "A high-capacity platform with an ergonomic handle for moving heavy loads safely. Autonomous navigation, layered safety and open integration let it adapt to your existing environment instead of forcing your operation to adapt to the robot.",
    imageAlt: "PUDU T600 Upright industrial robot with an ergonomic handle",
    features: [
      {
        title: "Heavy transport",
        description:
          "A 600 kg payload brings automation to pallets, trolleys and bulky production loads.",
      },
      {
        title: "Operator assistance",
        description:
          "The ergonomic control makes it easy to guide the robot even with a heavy load.",
      },
      {
        title: "Open integration",
        description:
          "VDA5050 support and on-premise deployment simplify the link to enterprise systems.",
      },
    ],
    applications: [
      {
        title: "Heavy production loads",
        description:
          "Moving pallets, trolleys and bulky parts across the whole operation.",
      },
      {
        title: "Inter-process logistics",
        description: "Automating longer routes that carry a high load weight.",
      },
      {
        title: "Automotive and mechanical engineering",
        description:
          "Repeated transport of heavy components between workplaces and lines.",
      },
      {
        title: "Enterprise system integration",
        description:
          "Deployment in environments with the VDA5050 protocol and local fleet control.",
      },
    ],
    seoTitle:
      "PUDU T600 Upright | Heavy-duty autonomous transport | PUDU Industrial",
    seoDescription:
      "PUDU T600 Upright — an autonomous platform with a 600 kg payload and an ergonomic handle for moving heavy loads safely. Specifications and applications.",
  },
  "pudu-t600-underride": {
    name: "PUDU T600 Underride",
    category: "Low-profile lifting AMR",
    headline: "Under the load. Above expectations.",
    shortDescription:
      "A low-profile autonomous robot that drives under a rack, lifts it and moves it.",
    description:
      "A low-profile autonomous robot that drives under a rack, lifts it and moves it. Autonomous navigation, layered safety and open integration let it adapt to your existing environment instead of forcing your operation to adapt to the robot.",
    imageAlt: "PUDU T600 Underride low-profile autonomous robot",
    features: [
      {
        title: "Drives under the rack",
        description:
          "The low profile allows autonomous entry underneath a compatible rack or trolley.",
      },
      {
        title: "Lift and transport",
        description:
          "The integrated 60 mm lift picks the load up safely and moves it to the target location.",
      },
      {
        title: "Fleet logistics",
        description:
          "Rack-group recognition and route coordination support scalable warehouse automation.",
      },
    ],
    applications: [
      {
        title: "Moving racks and trolleys",
        description:
          "Autonomous entry, lift and relocation of a complete transport unit.",
      },
      {
        title: "Warehouse automation",
        description:
          "Reshaping material flows without touching the existing infrastructure.",
      },
      {
        title: "Production and buffer storage",
        description:
          "Moving work in progress between cells, lines and staging areas.",
      },
      {
        title: "Fleet logistics",
        description:
          "Coordinating several robots and rack groups across a single floor.",
      },
    ],
    seoTitle: "PUDU T600 Underride | Low-profile lifting AMR | PUDU Industrial",
    seoDescription:
      "PUDU T600 Underride — a low-profile autonomous robot with a 600 kg payload that drives under a rack, lifts it and moves it. Specifications and applications.",
  },
};
