import type { LocalizedProductContent, ProductSlug } from "@/types/product";

/**
 * Slovak product copy. Technical data lives in data/products.ts — this
 * file holds only text, so it can be regenerated by the translations manager.
 */
export const productTextsSk: Record<
  ProductSlug,
  LocalizedProductContent
> = {
  "pudu-t150": {
    name: "AMR T 150",
    category:
      "Autonómny mobilný doručovací robot pre ľahkú prepravu materiálu do 150 kg.",
    headline: "Nosnosť nákladu do 150kg. Maximálna plynulosť pohybu.",
    shortDescription:
      "Kompaktný, uživateľksky inteligentný priemyselný AMR robot pre rýchle doručenie materiálu.",
    description:
      "Kompaktný priemyselný AMR robot 150 pre doručenie tovaru pravidelných logistických okruhov. Vďaka autonómnej navigácii, a možnosti integrácie sa prispôsobí existujúcemu prostrediu bez toho, aby obmedzoval iných úlohy.",
    imageAlt: "Priemyselný AMR robot PUDU T150 s prepravovaným nákladom",
    features: [
      {
        title: "Rýchle nasadenie",
        description:
          "Mapovanie a základné spustenie bez stavebných úprav alebo komplikovanej infraštruktúry.",
      },
      {
        title: "Presná navigácia",
        description:
          "Kombinácia VSLAM a LiDAR zabezpečuje stabilný pohyb v dynamickom priemyselnom prostredí.",
      },
      {
        title: "Prevádzka 24/7",
        description:
          "Jednoduchá výmena batérie, automatické aj káblové nabíjanie podporujú nepretržitú logistiku.",
      },
    ],
    applications: [
      {
        title: "Zásobovanie výrobných liniek",
        description:
          "Pravidelné doručovanie dielov, boxov, komponentov na montážne pracoviská alebo stanice.",
      },
      {
        title: "Interná preprava",
        description:
          "Opakované okruhy medzi skladom, prípravou materiálu alebo výrobou.",
      },
      {
        title:
          "Montáž, výroba, sklady, zásobovanie, obchod, intralogistika, etc.",
        description: "Bezpečný transport materiálu v úzkych priestoroch.",
      },
      {
        title: "Nemocnice, laboratóriá, školy",
        description:
          "Diskrétna preprava vzoriek, materiálu a spotrebného tovaru.",
      },
    ],
    seoTitle: "AMR T150 | Ľahká intralogistika | PUDU Industrial",
    seoDescription:
      "AMR T150 — kompaktný autonómny robot s nosnosťou do 150 kg pre diely, komponenty a pravidelné logistické okruhy. Technické parametre, funkcie a oblasti využitia.",
  },
  "pudu-t300": {
    name: "AMR T 300 (order 2 person)",
    category:
      "Najpredávanejší AMR T 300 Priemyselný autonómny mobilný robot na prepravu materiálu do 300 kg.",
    headline: "Transport, ktorý sa prispôsobí výrobe.",
    shortDescription:
      "Flexibilný autonómny mobilný vozík pre výrobu, sklady a doručovanie materiálu. Autonómny vozík T 300 zvládne širokú škálu prepravovaného bremena a zásobovanie liniek.",
    description:
      "Flexibilný autonómny transport pre doručenie materiálu do výroby, skladov alebo ak ide o celkové zásobovanie. Vďaka autonómnej navigácii, bezpečnostným rozhraniam a možnosti integrácie sa prispôsobí existujúcemu prostrediu bez obmedzení.",
    imageAlt:
      "Priemyselný robot AMR T 300 s variabilným nákladom s opciou dopravníka a ťahania platformy",
    galleryAlt: "AMR T 300 skenuje okolie v skladovej hale",
    features: [
      {
        title: "Autonómna preprava",
        description:
          "Samostatne doručí materiál na zvolené miesto a dynamicky reaguje na zmeny trasy, bezpečne a plynulo.",
      },
      {
        title: "Režim nasledovania",
        description:
          "Vizuálne rozpoznávanie umožňuje organizované nasledovanie pracovníka alebo ďalších robotov.",
      },
      {
        title: "Elektrická asistencia",
        description:
          "Pri manuálnom presune pomáha elektrický pohon a znižuje fyzickú námahu obsluhy.",
      },
    ],
    applications: [
      {
        title: "Výroba a montážne linky",
        description:
          "Autonómne zásobovanie pracovísk materiálom podľa taktu výroby.",
      },
      {
        title: "Sklady a distribučné centrá",
        description:
          "Preprava medzi príjmom, skladovými zónami a expedíciou bez obsluhy.",
      },
      {
        title: "Automotive a elektronika",
        description:
          "Stabilný tok materiálu v prostredí s vysokou vyťaženosťou trás.",
      },
      {
        title: "Zmiešaná prevádzka s ľuďmi",
        description:
          "Režim nasledovania a elektrická asistencia pri manuálnych úlohách.",
      },
    ],
    seoTitle: "AMR T 300 | Univerzálny AMR | PUDU Industrial",
    seoDescription:
      "AMR T 300 — univerzálny autonómny robot s nosnosťou do 300 kg pre výrobu, sklady a zásobovanie liniek. Technické parametre, funkcie a oblasti využitia.",
  },
  "pudu-t600-upright": {
    name: "AMR T 600 (Order 2 Person)",
    category:
      "AMR T 600 Priemyselný autonómny mobilný robot na prepravu ťažšieho materiálu do 600 kg.",
    headline: "Zvládne i ťažkú váhu bez obmedzenia na výkon.",
    shortDescription:
      "Vysokokapacitná platforma s možnosťou prepravy paliet, krabíc, ťažkých bremien s ergonomickou rukoväťou pre bezpečný presun ťažkých nákladov s možnosťou ťahu za vozíkom a zdvihom.",
    description:
      "Robotický vozík T 600 je stavaný pre ťažký náklad s ktorým si hravo poradí. Jeho vysokokapacitná zosilnená platforma s ergonomickou rukoväťou a farebným inteligentným displejom umožňuje komunikáciu pre bezpečný presun ťažkých nákladov. Vďaka autonómnej navigácii, bezpečnostnému rozhranie sa prispôsobí svojmu okoliu a doručí tovar na požadované miesto.",
    imageAlt:
      "Priemyselný robot AMR T 600 s ergonomickou rukoväťou a farebným displejom.",
    features: [
      {
        title: "Ťažký transport",
        description:
          "Nosnosť do 600 kg prináša automatizáciu paliet, vozíkov a objemných výrobných nákladov.",
      },
      {
        title: "Asistencia obsluhe",
        description:
          "Ergonomický ovládač pomáha pracovníkovi jednoducho viesť robot aj s ťažkým nákladom.",
      },
      {
        title: "Otvorená integrácia",
        description:
          "Podpora protokolu VDA5050 a lokálneho nasadenia uľahčuje zapojenie do podnikových systémov.",
      },
    ],
    applications: [
      {
        title: "Ťažké náklady pre plynulú prepravu",
        description:
          "Presun paliet, mobilých platforiem a väčších bremien v rámci celej prevádzky.",
      },
      {
        title: "Medzioperačná logistika",
        description:
          "Automatizovaný presun materiálu s vysokou hmotnosťou prepravovaného nákladu.",
      },
      {
        title:
          "Automotive a strojárstvo, zbrojársky priemysel, výroba, montážne pracoviská, intralogistika, obchody, etc.",
        description:
          "Opakovaný transport ťažkých komponentov medzi pracoviskami a linkami.",
      },
      {
        title: "Integrácia do podnikových systémov",
        description:
          "Nasadenie v prostredí s protokolom VDA5050 a lokálnym riadením flotily.",
      },
    ],
    seoTitle: "AMR T600 | Ťažký autonómny transport | PUDU Industrial",
    seoDescription:
      "AMR T600 — autonómna platforma s nosnosťou do 600 kg a ergonomickou rukoväťou pre bezpečný presun ťažkých nákladov. Technické parametre a oblasti využitia.",
  },
  "pudu-t600-underride": {
    name: "AMR T 600 Podjazdový",
    category:
      "Nízky zdvíhací podjazdový robotický vozík s výškou zdvihu do 60mm a nosnosťou do 600kg",
    headline:
      "Bezkonkurenčný podjazdový vozík s ergonomickou výškou len 250mm vo svojej kategórii.",
    shortDescription:
      "Autonómny robotický vozík AMR 600 typu podjazdový, predstavuje jednoduché a spoľahlivé riešenie Plug and Play, ktoré sa vyznačuje rýchlym zavedením do prevádzky. Ide o systémové riešenie navrhnuté tak, aby vám poskytlo maximálny výkon.",
    description:
      "Nízky autonómny podjazdový AMR robot, ktorý sa zasunie pod regál, zdvihne ho a premiestni. Vďaka autonómnej navigácii, bezpečnostným rizhraním má možnosti integrácie kde sa prispôsobí existujúcemu prostrediu bez toho, aby obmedzil výrobu.",
    imageAlt: "Nízky robotický vozík AMR 600 podjazdový",
    features: [
      {
        title: "Podjazd pod platformu, regál, a iné konštrukcie",
        description:
          "Nízky profil umožňuje autonómny vjazd pod kompatibilný regál alebo rám.",
      },
      {
        title: "Zdvih a transport",
        description:
          "Integrovaný zdvih 60 mm bezpečne prevezme náklad a presunie ho na určené miesto.",
      },
      {
        title: "Aplikačná logistika",
        description:
          "Rozpoznávanie skupín regálov a koordinácia trás podporujú škálovateľnú automatizáciu skladu.",
      },
    ],
    applications: [
      {
        title:
          "Presun paliet, regálov a vozíkov, statických či mobilných rámov.",
        description:
          "Autonómny podjazd, zdvih a premiestnenie celej prepravnej jednotky.",
      },
      {
        title: "Skladová automatizácia Aplikačná logistika, výroba",
        description:
          "Zmena tokov materiálu bez zásahu do existujúcej infraštruktúry.",
      },
      {
        title: "Výroba a medzisklad",
        description:
          "Presun rozpracovanej výroby medzi bunkami, linkami a odkladacími zónami.",
      },
      {
        title: "Flotilová logistika",
        description:
          "Koordinácia viacerých robotov a skupín regálov na jednej ploche.",
      },
    ],
    seoTitle: "AMR 600 Podbehové | Nízky zdvíhací AMR | PUDU Industrial",
    seoDescription:
      "AMR 600 Podbehové — nízky autonómny robot s nosnosťou do 600 kg, ktorý podbere rám s paletou, zdvihne ho a premiestni. Technické parametre a oblasti využitia.",
  },
};
