import type { LocalizedProductContent, ProductSlug } from "@/types/product";

/**
 * Slovak product copy. Technical data lives in data/products.ts — this
 * file holds only text, so it can be regenerated by the translations manager.
 */
export const productTextsSk: Record<
  ProductSlug,
  LocalizedProductContent
> = {
  "pudu-t150": {
    name: "PUDU T150",
    category: "Ľahká intralogistika",
    headline: "Ľahký náklad. Maximálna plynulosť.",
    shortDescription:
      "Kompaktný priemyselný robot pre diely, komponenty a pravidelné logistické okruhy.",
    description:
      "Kompaktný priemyselný robot pre diely, komponenty a pravidelné logistické okruhy. Vďaka autonómnej navigácii, bezpečnostným vrstvám a možnosti integrácie sa prispôsobí existujúcemu prostrediu bez toho, aby výrobu nútil prispôsobiť sa robotu.",
    imageAlt: "Priemyselný robot PUDU T150 s prepravovaným nákladom",
    features: [
      {
        title: "Rýchle nasadenie",
        description:
          "Mapovanie a základné spustenie bez stavebných úprav alebo komplikovanej infraštruktúry.",
      },
      {
        title: "Presná navigácia",
        description:
          "Kombinácia VSLAM a LiDAR zabezpečuje stabilný pohyb v dynamickom priemyselnom prostredí.",
      },
      {
        title: "Prevádzka 24/7",
        description:
          "Výmena batérie, automatické aj káblové nabíjanie podporujú nepretržitú logistiku.",
      },
    ],
    applications: [
      {
        title: "Zásobovanie výrobných liniek",
        description:
          "Pravidelné doručovanie dielov a komponentov na montážne pracoviská.",
      },
      {
        title: "Interná preprava komponentov",
        description:
          "Opakované okruhy medzi skladom, prípravou materiálu a výrobou.",
      },
      {
        title: "Elektronika a presná výroba",
        description:
          "Šetrný transport citlivých dielov v úzkych a čistých priestoroch.",
      },
      {
        title: "Nemocnice a laboratóriá",
        description:
          "Diskrétny prevoz vzoriek, materiálu a spotrebného tovaru.",
      },
    ],
    seoTitle: "PUDU T150 | Ľahká intralogistika | PUDU Industrial",
    seoDescription:
      "PUDU T150 — kompaktný autonómny robot s nosnosťou 150 kg pre diely, komponenty a pravidelné logistické okruhy. Technické parametre, funkcie a oblasti využitia.",
  },
  "pudu-t300": {
    name: "PUDU T300",
    category: "Univerzálny AMR",
    headline: "Pohyb, ktorý sa prispôsobí výrobe.",
    shortDescription:
      "Flexibilný autonómny transport pre výrobu, sklady a zásobovanie liniek.",
    description:
      "Flexibilný autonómny transport pre výrobu, sklady a zásobovanie liniek. Vďaka autonómnej navigácii, bezpečnostným vrstvám a možnosti integrácie sa prispôsobí existujúcemu prostrediu bez toho, aby výrobu nútil prispôsobiť sa robotu.",
    imageAlt: "Priemyselný robot PUDU T300 s kartónovým nákladom",
    galleryAlt: "PUDU T300 skenuje okolie v skladovej hale",
    features: [
      {
        title: "Autonómna preprava",
        description:
          "Samostatne doručí materiál na zvolené miesto a dynamicky reaguje na zmeny trasy.",
      },
      {
        title: "Režim nasledovania",
        description:
          "Vizuálne rozpoznávanie umožňuje organizované nasledovanie pracovníka alebo ďalších robotov.",
      },
      {
        title: "Elektrická asistencia",
        description:
          "Pri manuálnom presune pomáha elektrický pohon a znižuje fyzickú námahu obsluhy.",
      },
    ],
    applications: [
      {
        title: "Výroba a montážne linky",
        description:
          "Autonómne zásobovanie pracovísk materiálom podľa taktu výroby.",
      },
      {
        title: "Sklady a distribučné centrá",
        description:
          "Preprava medzi príjmom, skladovými zónami a expedíciou bez obsluhy.",
      },
      {
        title: "Automotive a elektronika",
        description:
          "Stabilný tok komponentov v prostredí s vysokou vyťaženosťou trás.",
      },
      {
        title: "Zmiešaná prevádzka s ľuďmi",
        description:
          "Režim nasledovania a elektrická asistencia pri manuálnych úlohách.",
      },
    ],
    seoTitle: "PUDU T300 | Univerzálny AMR | PUDU Industrial",
    seoDescription:
      "PUDU T300 — univerzálny autonómny robot s nosnosťou 300 kg pre výrobu, sklady a zásobovanie liniek. Technické parametre, funkcie a oblasti využitia.",
  },
  "pudu-t600-upright": {
    name: "PUDU T600 Upright",
    category: "Ťažký autonómny transport",
    headline: "Ťažká práca. Inteligentne.",
    shortDescription:
      "Vysokokapacitná platforma s ergonomickou rukoväťou pre bezpečný presun ťažkých nákladov.",
    description:
      "Vysokokapacitná platforma s ergonomickou rukoväťou pre bezpečný presun ťažkých nákladov. Vďaka autonómnej navigácii, bezpečnostným vrstvám a možnosti integrácie sa prispôsobí existujúcemu prostrediu bez toho, aby výrobu nútil prispôsobiť sa robotu.",
    imageAlt: "Priemyselný robot PUDU T600 Upright s ergonomickou rukoväťou",
    features: [
      {
        title: "Ťažký transport",
        description:
          "Nosnosť 600 kg prináša automatizáciu paliet, vozíkov a objemných výrobných nákladov.",
      },
      {
        title: "Asistencia obsluhe",
        description:
          "Ergonomický ovládač pomáha pracovníkovi jednoducho viesť robot aj s ťažkým nákladom.",
      },
      {
        title: "Otvorená integrácia",
        description:
          "Podpora protokolu VDA5050 a lokálneho nasadenia uľahčuje zapojenie do podnikových systémov.",
      },
    ],
    applications: [
      {
        title: "Ťažké výrobné náklady",
        description:
          "Presun paliet, vozíkov a objemných dielov v rámci celej prevádzky.",
      },
      {
        title: "Medzioperačná logistika",
        description:
          "Automatizácia dlhších trás s vysokou hmotnosťou prepravovaného nákladu.",
      },
      {
        title: "Automotive a strojárstvo",
        description:
          "Opakovaný transport ťažkých komponentov medzi pracoviskami a linkami.",
      },
      {
        title: "Integrácia do podnikových systémov",
        description:
          "Nasadenie v prostredí s protokolom VDA5050 a lokálnym riadením flotily.",
      },
    ],
    seoTitle: "PUDU T600 Upright | Ťažký autonómny transport | PUDU Industrial",
    seoDescription:
      "PUDU T600 Upright — autonómna platforma s nosnosťou 600 kg a ergonomickou rukoväťou pre bezpečný presun ťažkých nákladov. Technické parametre a oblasti využitia.",
  },
  "pudu-t600-underride": {
    name: "PUDU T600 Underride",
    category: "Nízky zdvíhací AMR",
    headline: "Pod nákladom. Nad očakávaniami.",
    shortDescription:
      "Nízky autonómny podjazdový robot, ktorý sa zasunie pod regál, zdvihne ho a premiestni.",
    description:
      "Nízky autonómny podjazdový robot, ktorý sa zasunie pod regál, zdvihne ho a premiestni. Vďaka autonómnej navigácii, bezpečnostným vrstvám a možnosti integrácie sa prispôsobí existujúcemu prostrediu bez toho, aby výrobu nútil prispôsobiť sa robotu.",
    imageAlt: "Nízky podjazdový robot PUDU T600 Underride",
    features: [
      {
        title: "Podjazd pod regál",
        description:
          "Nízky profil umožňuje autonómny vjazd pod kompatibilný regál alebo vozík.",
      },
      {
        title: "Zdvih a transport",
        description:
          "Integrovaný zdvih 60 mm bezpečne prevezme náklad a presunie ho na určené miesto.",
      },
      {
        title: "Flotilová logistika",
        description:
          "Rozpoznávanie skupín regálov a koordinácia trás podporujú škálovateľnú automatizáciu skladu.",
      },
    ],
    applications: [
      {
        title: "Presun regálov a vozíkov",
        description:
          "Autonómny podjazd, zdvih a premiestnenie celej prepravnej jednotky.",
      },
      {
        title: "Skladová automatizácia",
        description:
          "Zmena tokov materiálu bez zásahu do existujúcej infraštruktúry.",
      },
      {
        title: "Výroba a medzisklad",
        description:
          "Presun rozpracovanej výroby medzi bunkami, linkami a odkladacími zónami.",
      },
      {
        title: "Flotilová logistika",
        description:
          "Koordinácia viacerých robotov a skupín regálov na jednej ploche.",
      },
    ],
    seoTitle: "PUDU T600 Underride | Nízky zdvíhací AMR | PUDU Industrial",
    seoDescription:
      "PUDU T600 Underride — nízky autonómny robot s nosnosťou 600 kg, ktorý podjazdí regál, zdvihne ho a premiestni. Technické parametre a oblasti využitia.",
  },
};
